# Generated by Django 3.1.7 on 2021-03-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TASK', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='awsimage',
        ),
    ]
